# Generated by Django 5.0.7 on 2025-08-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_medicalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='experience_years',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
